/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrgRouteRouteImport } from './routes/org/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as OrgTeamsIndexRouteImport } from './routes/org/teams/index'
import { Route as OrgSettingsIndexRouteImport } from './routes/org/settings/index'
import { Route as OrgMembersIndexRouteImport } from './routes/org/members/index'
import { Route as OrgDashboardIndexRouteImport } from './routes/org/dashboard/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminOrganizationsIndexRouteImport } from './routes/admin/organizations/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as publicPricingIndexRouteImport } from './routes/(public)/pricing/index'
import { Route as publicLandingIndexRouteImport } from './routes/(public)/landing/index'
import { Route as publicAboutIndexRouteImport } from './routes/(public)/about/index'
import { Route as OrgTeamsTeamIdRouteImport } from './routes/org/teams/$teamId'
import { Route as InvitationsAcceptInvitationIdRouteImport } from './routes/invitations/accept/$invitationId'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminOrganizationsOrgIdRouteImport } from './routes/admin/organizations/$orgId'

const OrgRouteRoute = OrgRouteRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgTeamsIndexRoute = OrgTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgSettingsIndexRoute = OrgSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgMembersIndexRoute = OrgMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgDashboardIndexRoute = OrgDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => OrgRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationsIndexRoute = AdminOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const publicPricingIndexRoute = publicPricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicLandingIndexRoute = publicLandingIndexRouteImport.update({
  id: '/landing/',
  path: '/landing/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicAboutIndexRoute = publicAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => publicRouteRoute,
} as any)
const OrgTeamsTeamIdRoute = OrgTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => OrgRouteRoute,
} as any)
const InvitationsAcceptInvitationIdRoute =
  InvitationsAcceptInvitationIdRouteImport.update({
    id: '/invitations/accept/$invitationId',
    path: '/invitations/accept/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationsOrgIdRoute = AdminOrganizationsOrgIdRouteImport.update({
  id: '/organizations/$orgId',
  path: '/organizations/$orgId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/org': typeof OrgRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/': typeof publicIndexRoute
  '/admin/organizations/$orgId': typeof AdminOrganizationsOrgIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/invitations/accept/$invitationId': typeof InvitationsAcceptInvitationIdRoute
  '/org/teams/$teamId': typeof OrgTeamsTeamIdRoute
  '/about/': typeof publicAboutIndexRoute
  '/landing/': typeof publicLandingIndexRoute
  '/pricing/': typeof publicPricingIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/org/dashboard/': typeof OrgDashboardIndexRoute
  '/org/members/': typeof OrgMembersIndexRoute
  '/org/settings/': typeof OrgSettingsIndexRoute
  '/org/teams/': typeof OrgTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteRouteWithChildren
  '/org': typeof OrgRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/': typeof publicIndexRoute
  '/admin/organizations/$orgId': typeof AdminOrganizationsOrgIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/invitations/accept/$invitationId': typeof InvitationsAcceptInvitationIdRoute
  '/org/teams/$teamId': typeof OrgTeamsTeamIdRoute
  '/about': typeof publicAboutIndexRoute
  '/landing': typeof publicLandingIndexRoute
  '/pricing': typeof publicPricingIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/organizations': typeof AdminOrganizationsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/org/dashboard': typeof OrgDashboardIndexRoute
  '/org/members': typeof OrgMembersIndexRoute
  '/org/settings': typeof OrgSettingsIndexRoute
  '/org/teams': typeof OrgTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/org': typeof OrgRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(public)/': typeof publicIndexRoute
  '/admin/organizations/$orgId': typeof AdminOrganizationsOrgIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/invitations/accept/$invitationId': typeof InvitationsAcceptInvitationIdRoute
  '/org/teams/$teamId': typeof OrgTeamsTeamIdRoute
  '/(public)/about/': typeof publicAboutIndexRoute
  '/(public)/landing/': typeof publicLandingIndexRoute
  '/(public)/pricing/': typeof publicPricingIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/org/dashboard/': typeof OrgDashboardIndexRoute
  '/org/members/': typeof OrgMembersIndexRoute
  '/org/settings/': typeof OrgSettingsIndexRoute
  '/org/teams/': typeof OrgTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/org'
    | '/login'
    | '/'
    | '/admin/organizations/$orgId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/invitations/accept/$invitationId'
    | '/org/teams/$teamId'
    | '/about/'
    | '/landing/'
    | '/pricing/'
    | '/admin/dashboard/'
    | '/admin/organizations/'
    | '/admin/users/'
    | '/org/dashboard/'
    | '/org/members/'
    | '/org/settings/'
    | '/org/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/org'
    | '/login'
    | '/'
    | '/admin/organizations/$orgId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/invitations/accept/$invitationId'
    | '/org/teams/$teamId'
    | '/about'
    | '/landing'
    | '/pricing'
    | '/admin/dashboard'
    | '/admin/organizations'
    | '/admin/users'
    | '/org/dashboard'
    | '/org/members'
    | '/org/settings'
    | '/org/teams'
  id:
    | '__root__'
    | '/(public)'
    | '/admin'
    | '/org'
    | '/(auth)/login'
    | '/(public)/'
    | '/admin/organizations/$orgId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/invitations/accept/$invitationId'
    | '/org/teams/$teamId'
    | '/(public)/about/'
    | '/(public)/landing/'
    | '/(public)/pricing/'
    | '/admin/dashboard/'
    | '/admin/organizations/'
    | '/admin/users/'
    | '/org/dashboard/'
    | '/org/members/'
    | '/org/settings/'
    | '/org/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  OrgRouteRoute: typeof OrgRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  InvitationsAcceptInvitationIdRoute: typeof InvitationsAcceptInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/teams/': {
      id: '/org/teams/'
      path: '/teams'
      fullPath: '/org/teams/'
      preLoaderRoute: typeof OrgTeamsIndexRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/org/settings/': {
      id: '/org/settings/'
      path: '/settings'
      fullPath: '/org/settings/'
      preLoaderRoute: typeof OrgSettingsIndexRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/org/members/': {
      id: '/org/members/'
      path: '/members'
      fullPath: '/org/members/'
      preLoaderRoute: typeof OrgMembersIndexRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/org/dashboard/': {
      id: '/org/dashboard/'
      path: '/dashboard'
      fullPath: '/org/dashboard/'
      preLoaderRoute: typeof OrgDashboardIndexRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organizations/': {
      id: '/admin/organizations/'
      path: '/organizations'
      fullPath: '/admin/organizations/'
      preLoaderRoute: typeof AdminOrganizationsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(public)/pricing/': {
      id: '/(public)/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof publicPricingIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/landing/': {
      id: '/(public)/landing/'
      path: '/landing'
      fullPath: '/landing/'
      preLoaderRoute: typeof publicLandingIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/about/': {
      id: '/(public)/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof publicAboutIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/org/teams/$teamId': {
      id: '/org/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/org/teams/$teamId'
      preLoaderRoute: typeof OrgTeamsTeamIdRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/invitations/accept/$invitationId': {
      id: '/invitations/accept/$invitationId'
      path: '/invitations/accept/$invitationId'
      fullPath: '/invitations/accept/$invitationId'
      preLoaderRoute: typeof InvitationsAcceptInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizations/$orgId': {
      id: '/admin/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/admin/organizations/$orgId'
      preLoaderRoute: typeof AdminOrganizationsOrgIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
  publicAboutIndexRoute: typeof publicAboutIndexRoute
  publicLandingIndexRoute: typeof publicLandingIndexRoute
  publicPricingIndexRoute: typeof publicPricingIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
  publicAboutIndexRoute: publicAboutIndexRoute,
  publicLandingIndexRoute: publicLandingIndexRoute,
  publicPricingIndexRoute: publicPricingIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminOrganizationsOrgIdRoute: typeof AdminOrganizationsOrgIdRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminOrganizationsIndexRoute: typeof AdminOrganizationsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminOrganizationsOrgIdRoute: AdminOrganizationsOrgIdRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminOrganizationsIndexRoute: AdminOrganizationsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface OrgRouteRouteChildren {
  OrgTeamsTeamIdRoute: typeof OrgTeamsTeamIdRoute
  OrgDashboardIndexRoute: typeof OrgDashboardIndexRoute
  OrgMembersIndexRoute: typeof OrgMembersIndexRoute
  OrgSettingsIndexRoute: typeof OrgSettingsIndexRoute
  OrgTeamsIndexRoute: typeof OrgTeamsIndexRoute
}

const OrgRouteRouteChildren: OrgRouteRouteChildren = {
  OrgTeamsTeamIdRoute: OrgTeamsTeamIdRoute,
  OrgDashboardIndexRoute: OrgDashboardIndexRoute,
  OrgMembersIndexRoute: OrgMembersIndexRoute,
  OrgSettingsIndexRoute: OrgSettingsIndexRoute,
  OrgTeamsIndexRoute: OrgTeamsIndexRoute,
}

const OrgRouteRouteWithChildren = OrgRouteRoute._addFileChildren(
  OrgRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  OrgRouteRoute: OrgRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  InvitationsAcceptInvitationIdRoute: InvitationsAcceptInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
